version: "3"

services:
  flask: 
    image: alpine:latest
    depends_on:
      - redis
    ports:
      - 5000:5000
    networks:
      - localhost
    restart: always    


  redis:
    hostname: redis
    image: redis:latest
    networks:
      - localhost
    ports:
      - 6379:6379
    volumes:
      - "redisdata:/data"
    restart: always    

volumes:
  redisdata:
networks:
  localhost:
