version: '3.6'  
services:  
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:  
  redis_data:
